# Generated by Django 5.1.2 on 2024-10-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
