name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run deployment via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ''
        script: |
          # إعداد المشروع
          cd /opt/africanmaps
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          
          sudo cp /opt/africanmaps/deployment/gunicorn.service /etc/systemd/system/gunicorn.service
          sudo systemctl daemon-reload
          sudo systemctl enable gunicorn
          sudo systemctl start gunicorn

          sudo rm /etc/nginx/sites-enabled/default
          sudo tee /etc/nginx/sites-available/africanmaps <<EOF
          server {
              listen 80;
              server_name ${{ secrets.SERVER_IP }} your-domain.com;

              client_max_body_size 2G;

              location = /favicon.ico { access_log off; log_not_found off; }
              location /static/ {
                  root /opt/africanmaps;
              }

              location / {
                  include proxy_params;
                  proxy_pass http://unix:/opt/africanmaps/africanmaps.sock;
              }
          }
          EOF

          sudo ln -s /etc/nginx/sites-available/africanmaps /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl restart nginx

          sudo systemctl restart gunicorn
