name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run deployment via SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: 138.68.181.88
        username: "root" # اسم المستخدم (مثلاً root)
        key: |
         -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
        NhAAAAAwEAAQAAAgEAsK/SNcpSa8/ZAppPORWbclnTAmuS/RiduRWu8rbJ8UY8r+5cYGHC
        5+7n/pqrqdWzOcPzC5q4Gj7ppiVKsrrqrZXIps41ZvuVcpRbf84AfZkoCGf4lBWO40xmQ/
        xvjWlnj1KWIsGXFEj7FDq5PHdMtb/WS4z0zg7znDa3JprUHS40jsBl3ec7VDkWR1CBAdsd
        9nDjABRxuOF35aTXsGV4eakL1MosuG7nB8aoy0dJJ//buGoDUnxNwt9TJPkqFwcpJUH43i
        e6ucBjnuBrQnjHEbAI12edzYsAEqAy/pyYweN1n9jgdQ4zPkpQTtbH6Bvf/4LI2XWgrSxS
        ZCaRHLOoM7sGb0IxliU9ozvB/KzazQN0YSO5i9FHev7K+MLEPmYi84s2tpaOPJ1wnYZ25n
        3cdnR3XY6LLMrPR0+8mP3OpC3TX+9vpDpXCNqYIU/t4f6ZCNCvAdK2WD0lZCWA59l1BQIV
        HkW/ccECQL+jerOMXAmQxVqpb5U3/9ClRA9cazUiJLbyR/zEIWSgGo3s8zijB0GchwbcID
        cHoeC0CqXPu57oSxrsjIhJhq/KZJio3TuPJXiIL17TsVegO0pxERxbqzpTSV0yZXYrn2Tb
        4eNty6AmMARUSiILBeCQU7oKV34amQONZpKSq9SKlLMlOPxltFCHD9jExyK/29RKc84qEP
        8AAAdQUJxNYFCcTWAAAAAHc3NoLXJzYQAAAgEAsK/SNcpSa8/ZAppPORWbclnTAmuS/Rid
        uRWu8rbJ8UY8r+5cYGHC5+7n/pqrqdWzOcPzC5q4Gj7ppiVKsrrqrZXIps41ZvuVcpRbf8
        4AfZkoCGf4lBWO40xmQ/xvjWlnj1KWIsGXFEj7FDq5PHdMtb/WS4z0zg7znDa3JprUHS40
        jsBl3ec7VDkWR1CBAdsd9nDjABRxuOF35aTXsGV4eakL1MosuG7nB8aoy0dJJ//buGoDUn
        xNwt9TJPkqFwcpJUH43ie6ucBjnuBrQnjHEbAI12edzYsAEqAy/pyYweN1n9jgdQ4zPkpQ
        TtbH6Bvf/4LI2XWgrSxSZCaRHLOoM7sGb0IxliU9ozvB/KzazQN0YSO5i9FHev7K+MLEPm
        Yi84s2tpaOPJ1wnYZ25n3cdnR3XY6LLMrPR0+8mP3OpC3TX+9vpDpXCNqYIU/t4f6ZCNCv
        AdK2WD0lZCWA59l1BQIVHkW/ccECQL+jerOMXAmQxVqpb5U3/9ClRA9cazUiJLbyR/zEIW
        SgGo3s8zijB0GchwbcIDcHoeC0CqXPu57oSxrsjIhJhq/KZJio3TuPJXiIL17TsVegO0px
        ERxbqzpTSV0yZXYrn2Tb4eNty6AmMARUSiILBeCQU7oKV34amQONZpKSq9SKlLMlOPxltF
        CHD9jExyK/29RKc84qEP8AAAADAQABAAACAAhEac8XhOzDgHF1O/C9WJUsq8lotCuAi9y9
        rX5w3Bkcgrluq0bdPCvzC0rn/NFJDQZOa2BnIGcl+3PJOeoMAfAWWpmne2syqWb/lxpvTq
        mR0YQ3LTPsoE91YzGaLbQNswlLQXgl28ZYtdrX9pPkNyQn8kR9t3Su0WpFSyOUygkFgPMP
        AJU1/RovQ6IZm7e1A31lAdIeosWWUzBdGrSHwu/aX5HY1efZVJkSDBLa5ornF2ZVG4uwAk
        l0fqTzvarvLFcwc48dh8iqPl8QPCSTlyj2NiuyDvmvn9S/RzOPqzwjQv00Pihr/izTeFeA
        CEGNkFkZywEV1mtT8BT8kvynUV7qX1HdxLJgYMF7+Jsi6DVR1BMPhP9bhiOM1E7Hek83Rt
        MZeFUWcLH8tIjM5+wUWU4gmTRIW+ltQH7S6kZhsfD4mvL0jncp2TNK4zWqkm366ghr+SZW
        a/4PGaeiWKDeRuQa3NR0fYcVwqiD0ly+PZ85yOvmWMDnowT1a8h3fow0sgIsU+wigWj21V
        RtexUGlfFZxgflAES1/LFTW3C/aiLamQjQUrm9lsEFQvELTuVw+o+WhftjjLJmu8coNtdH
        HwjxdKsR2dWwOzYnEbQj+PBQU1/B8E2dqviRJTfG1v4iYB9O8qadv864YOMYPJ4d5hTKwl
        tFzLMJudnmqhVTuN+lAAABAQDA7+ss8w0U12aGI5oXEgEkuszhAQbn83SK1y159aFypOGw
        iYFgYNhPgYC9ecw6fJMLoBB8Vme5YDeoYGrFKwzC8aSKtRI1aeLduTcgw4osoHMwAwvKML
        QrN5viQKrxwLClVi2xQ7B4dliw/8vuWBkYUMcZbySZYskqVccFmzMjtiIEo+XM4TCPA6zO
        T/Jj3zSCWIAqNkQYzD/JtbM/BPcg5wYYfmcp0BVEicyNQrMiPmSjmKaODcpv+zJ8vpwY9j
        7UGYKKYDnh+kWABm3aksUSPFIKu6BMXolHXkzqi7SCovFvzeRp+r9hJ4VTwVKtOOw7seAY
        Vp27klYmkaGw1BG6AAABAQDbVfOyhZSE4R+VHtWXXD3eK38eHyQ6ZRgIeoV0SNmigwyifa
        BZHg84LlRlkRFaWSVfgrAqbApiLEvwtDHmh3J8DVp1lmcqozUYmWIOdqt6HkJaxvf549oT
        5ySieFmgYWhVc58o1eg3lEZ8eouUeyRS1em4YxtdPMCx9ea8E2fxyHkpwpSQdECX9DMVSx
        5mfU9sLozuA5WmMQJmR843QaSOoKbfXpEFGohPUVitEM7vy8u9Ja4wghVC6VFZBTMg3G2d
        5y3+nwmSqYbVEzEq/sa+yJAbQ5ZancZ/CeqgNwXoW/CgNUGp1rU7ZAPU4MBrfahhHTS99J
        HzT1/T6QTuRTTDAAABAQDOOMpHNBzrRrHsVoGpZamQnFVNxOhcHNwujUIx4boznQg8YOHq
        TrTwLCmJBiRB/moCb8hZy5YEzDdRwDUA9hOjAPSHS8IwsISRKFEo/0ka/3weXmQgrGJv5L
        wmzgQmeuPdLnjzQXrnPnPwsGvWB/QvGY3Dh6IeBkzQ5o5ZK2bBGWY7kuxdSAiEWdGdUnBL
        KIUkP0vIRXf4MrhaF74iba0laQrC6y+Jp2iQ0AKXUrPaT03Jch+Lj9mnwSZNQKpZ+TQi8g
        2NKsBwL1/KcU7dKNPv9aPO2Lj1FaeOymnuTvV5AVhdK4Rr+b47WUiv4AL6qaCW83mAFI1O
        wTOe375IcH8VAAAAFWFiZGx3YWZpOTQzQGdtYWlsLmNvbQECAwQF
        -----END OPENSSH PRIVATE KEY-----
        passphrase: ''
        script: |
          # إعداد المشروع
          cd /opt/africanmaps
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput

          # إعداد gunicorn
          sudo cp /opt/africanmaps/deployment/gunicorn.service /etc/systemd/system/gunicorn.service
          sudo systemctl daemon-reload
          sudo systemctl enable gunicorn
          sudo systemctl start gunicorn

          # إعداد Nginx
          sudo rm /etc/nginx/sites-enabled/default
          sudo tee /etc/nginx/sites-available/africanmaps <<EOF
          server {
              listen 80;
              server_name ${{ secrets.SERVER_IP }} your-domain.com;

              client_max_body_size 2G;

              location = /favicon.ico { access_log off; log_not_found off; }
              location /static/ {
                  root /opt/africanmaps;
              }

              location / {
                  include proxy_params;
                  proxy_pass http://unix:/opt/africanmaps/africanmaps.sock;
              }
          }
          EOF

          sudo ln -s /etc/nginx/sites-available/africanmaps /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl restart nginx

          sudo systemctl restart gunicorn
